/*
 * Shape reference only. Real output is generated by
 * @deepseek-ai/dsh-typert-generator and must not be edited.
 *
 * This small file is not a complete runnable Typert contribution: it assumes a
 * matching Host Service is provided under `myService` and that the manifest
 * exports ./typert with zod as a runtime dependency. Real generated output owns
 * every Zod codec, declaration, model member, lookup, and sourceLocation.
 */
import { z } from 'zod'

const argsCodec = {
  mode: 'strict',
  typeSymbol: 'dsh-my-plugin/types#PingRequest',
  schema: z.object({ message: z.string() }).strict(),
}
const resultCodec = {
  mode: 'strict',
  typeSymbol: 'dsh-my-plugin/types#PingResult',
  schema: z.object({ reply: z.string() }).strict(),
}

export const TYPERT = {
  package: 'dsh-my-plugin',
  face: 'host',
  schemas: [],
  invocations: [
    {
      id: 'dsh-my-plugin#myService/ping',
      service: 'myService',
      namespace: 'myService',
      method: 'ping',
      invocation: { kind: 'direct' },
      parameters: [
        { name: 'request', wire: 'request', source: 'json', codec: argsCodec },
      ],
      result: resultCodec,
      sourceLocation: { file: 'src/index.ts', line: 1, column: 1 },
      // For generated methods, cancellation/scope are emitted only when the
      // source declaration requests them. Do not invent these fields.
    },
  ],
}

export default TYPERT
